Traceback (most recent call last):
  File "experiment.py", line 167, in <module>
    run_experiment(runner, params, output_directory)
  File "experiment.py", line 57, in run_experiment
    train_results, train_samples = runner.train(*formatted_data, output_directory)
  File "tf_runner.py", line 60, in train
    history = self.model.fit(
  File "traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "tft.py", line 205, in call
    encoder_output, state_h, state_c = self.encoder_lstm(
TypeError: Exception encountered when calling TFT.call().

[1mValue passed to parameter 'input' has DataType bfloat16 not in list of allowed values: float64, float32, float16, complex64, complex128[0m

Arguments received by TFT.call():
  â€¢ inputs=tf.Tensor(shape=(None, 288, 11), dtype=bfloat16)
  â€¢ training=True